### ISSUE TITLE
Error: requested size is too large

### ISSUE THREAD

**Issue by charshade17** [r-spatialecology/landscapemetrics#52]
Hello,

I am trying to use the lsm_p_contig function on a raster, but I keep receiving the following error:

error: Mat::init(): requested size is too large
Error in rcpp_get_coocurrence_matrix(raster::as.matrix(patches_class),  : 
  Mat::init(): requested size is too large

Here's the details about my raster:
dimensions  : 30499, 28435, 867239065  (nrow, ncol, ncell)
resolution  : 1, 1  (x, y)
extent      : 475532, 503967, 4412908, 4443407  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=18 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0 
data source : C:\Users\cshade\Desktop\FragStat_analysis\lc_2008_4bit_clip_reclass.tif 
names       : lc_2008_4bit_clip_reclass 
values      : 1, 3  (min, max)

Before I was trying to use 8 different classes, but I reclassified down to 3, although that did not seem to help.

Here are the details about my computer and software:
- Windows 10
- I'm using R 64 bit 3.5.1
- I have 120 GB of RAM (it's not maxing out during the process)
- I have 588 GB of free memory (also not maxing out)

[I have been loading the raster into my RAM before starting the process.](https://mgimond.github.io/megug2017/#managing-memory)

I know other people have seemed to have a similar issue with raster size, but it seems no one has ever found a solution. Any help would be greatly appreciated!:)

**Comment by marcosci** [comment]
Hi Charlotte,

I think I just pushed something to fix your error :relaxed: 

Can you please reinstall landscapemetrics and try it again?
To make sure that the C++ code is recompiled the following should do the trick:

```r
devtools::install_github("r-spatialecology/landscapemetrics", force = TRUE, local = F)
```
If it's still failing could you please post the text that the `install_github` call throws, plus your session info (`sessionInfo()`)? Is your raster data publicly available, so that we could try to dig deeper?

Cheers,
Marco

**Comment by charshade17** [comment]
So I reinstalled the package. Then I tried your code, but it gave me an error:

> install.packages("landscapemetrics")
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.5/landscapemetrics_0.2.zip'
Content type 'application/zip' length 2381395 bytes (2.3 MB)
downloaded 2.3 MB

package ‘landscapemetrics’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\cshade\AppData\Local\Temp\Rtmpma0pOy\downloaded_packages
> devtools::install_github("r-spatialecology/landscapemetrics", force = TRUE, local = F)
Error in loadNamespace(name) : there is no package called ‘devtools’

Sorry, is that what I was supposed to do? I really only know the basics of R, so I'm not familiar with "devtools", etc.

**Comment by marcosci** [comment]
No worries, I should have explained more :-)

So, instead of installing from CRAN (which install.packges does), you want to install the development version here from GitHub, thus:

```r
# install devtools
install.packages('devtools')

# install the correct version of landscapemetrics (with the fixes I made)
devtools::install_github("r-spatialecology/landscapemetrics", force = TRUE, local = F)
```

**Comment by charshade17** [comment]
Ok I reinstalled the package using your code, but I still received the same error. All of the text you asked for is pasted below:

> lsm_p_contig(lc08)

error: Mat::init(): requested size is too large
Error in rcpp_get_coocurrence_matrix(raster::as.matrix(patches_class),  : 
  Mat::init(): requested size is too large

> install_github
function (repo, ref = "master", subdir = NULL, auth_token = github_pat(), 
    host = "api.github.com", dependencies = NA, upgrade = c("ask", 
        "always", "never"), force = FALSE, quiet = FALSE, build = TRUE, 
    build_opts = c("--no-resave-data", "--no-manual", "--no-build-vignettes"), 
    repos = getOption("repos"), type = getOption("pkgType"), 
    ...) 
{
    remotes <- lapply(repo, github_remote, ref = ref, subdir = subdir, 
        auth_token = auth_token, host = host)
    install_remotes(remotes, auth_token = auth_token, host = host, 
        dependencies = dependencies, upgrade = upgrade, force = force, 
        quiet = quiet, build = build, build_opts = build_opts, 
        repos = repos, type = type, ...)
}
<bytecode: 0x0000000009137e18>
<environment: namespace:remotes>
> (sessionInfo())
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] raster_2.7-15        sp_1.3-1             landscapemetrics_0.3 usethis_1.4.0        devtools_2.0.1      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.19      magrittr_1.5      pkgload_1.0.1     lattice_0.20-35   R6_2.3.0          rlang_0.3.0.1     tools_3.5.1      
 [8] rgdal_1.3-6       grid_3.5.1        pkgbuild_1.0.2    sessioninfo_1.1.0 cli_1.0.1         withr_2.1.2       remotes_2.0.1    
[15] assertthat_0.2.0  digest_0.6.18     rprojroot_1.3-2   crayon_1.3.4      processx_3.2.0    callr_3.0.0       codetools_0.2-15 
[22] base64enc_0.1-3   fs_1.2.6          ps_1.2.0          curl_3.2          memoise_1.1.0     glue_1.3.0        compiler_3.5.1   
[29] desc_1.2.0        backports_1.1.2   prettyunits_1.0.2
> 

[The basis of the raster I am using is available online](http://www.pasda.psu.edu/uci/DataSummary.aspx?dataset=138) (I mosaiced in one more land cover class). I believe you'll have to project it into meters. I also formatted it into a 4 bit unsigned tiff raster.

**Comment by marcosci** [comment]
I started to write the geotiff, will let you know if I can reproduce the error :+1:

**Comment by marcosci** [comment]
@charshade17 I did not forget you - I am just struggling finding a machine with enough memory :-P

Anyways, if I write the file out as a geotiff it looks like this:

> big_raster
class       : RasterLayer 
dimensions  : 106134, 89859, 9537095106  (nrow, ncol, ncell)
resolution  : 3.673903e-06, 2.661862e-06  (x, y)
extent      : -75.28417, -74.95404, 39.86129, 40.1438  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 

... did you aggregate it somehow? Just trying to follow your preprocessing here.

**Comment by charshade17** [comment]
Oh that's odd, it should be at 1 m resolution. Not sure why its coming up so small. You can resample everything to a 1m resolution. Or I have uploaded the actual raster I am trying to process on my Google drive. [You should be able to download the tiff here.](https://drive.google.com/file/d/1peypM0wnd2cHCQnq7MNfePCaxCJ2-rez/view?usp=sharing)

But yes, I understand it's a challenge trying to find a machine to run it! I really appreciate your help:)

**Comment by marcosci** [comment]
So, I found the function causing the error - it's an internal Rcpp function (`rcpp_get_adjacency` - @Nowosad, do you have any idea why?). Unfortunately I am quite busy at the moment, but will tackle this during the week.

**Comment by marcosci** [comment]
Nope, I already tested that last week :-/ That didn't solve the problem.

**Comment by Nowosad** [comment]
The error is definetely related to the integer width. Now the question is how to fix it...

```r
library(raster)
library(landscapemetrics)

lc = brick("lc_2008_4bit_clip.tif")
lcm = as.matrix(lc)
output = landscapemetrics:::rcpp_get_adjacency(lcm, directions = as.matrix(4))
Error in landscapemetrics:::rcpp_get_adjacency(lcm, directions = as.matrix(4)) : 
  negative length vectors are not allowed
```

**Comment by marcosci** [comment]
Does the package compile for you with the integer width definition? 

I had to change it last week to `# define DARMA_64BIT_WORD 1` (https://github.com/r-spatialecology/landscapemetrics/blob/master/src/get_coocurrence_vector.cpp).

Anyway, get_adjacency doesn't even use armadillo, or? I already tried it with C++11, but no luck (https://github.com/RcppCore/Rcpp/issues/460).

**Comment by Nowosad** [comment]
Hm.. at least we've got some clues... I will try to rewrite some code in this cpp file later this week.

**Comment by charshade17** [comment]
Ok gotcha. Yes no rush! I really appreciate all of the help!

**Comment by Nowosad** [comment]
The main issue can be reproduced here:

```cpp
#include <RcppArmadillo.h>
using namespace Rcpp;

// [[Rcpp::depends(RcppArmadillo)]]

// [[Rcpp::export]]
IntegerMatrix test(int x) {
    IntegerMatrix result(x, 2);
    return(result);
}

/*** R
max_int = 2147483647
output = test(max_int + 1)
*/
```

I've tried to find a simple workaround, but I am unable yet.

**Comment by Nowosad** [comment]
The main issue here is that a maximum number of neighbors now is 2,147,483,647. For example, we have 600,000,000 cells and we want to calculate adjacency for 4 neighbors - the output needs to have 2,400,000,000 rows...
Possible (I think) way to fix it:
1. Medium rewrite - replace **Rcpp** classes with **RcppArmadillo** classes. For example `IntegerMatrix` -> `imat`. It also requires to use cpp11:

```
#define ARMA_64BIT_WORD 1
#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]
// [[Rcpp::plugins(cpp11)]] 
```
However, I've tried it for the example in my post above and failed (for now).

**Comment by marcosci** [comment]
Yup, I also tried bigmemory and failed (more likely due to lacking knowledge).
My next shot would be xtensor ...

If that fails, we would need to start to loop through everything :-/

**Comment by Nowosad** [comment]
Even a loop could not be enough - `get_adjacency()` output still needs to be larger than maxint...

**Comment by marcosci** [comment]
Sure, but we could return in a list, which doesn't have size limits of a matrix, or?

**Comment by bitbacchus** [comment]
> The main issue can be reproduced here:
> 
> ```c++
> #include <RcppArmadillo.h>
> using namespace Rcpp;
> 
> // [[Rcpp::depends(RcppArmadillo)]]
> 
> // [[Rcpp::export]]
> IntegerMatrix test(int x) {
>     IntegerMatrix result(x, 2);
>     return(result);
> }
> 
> /*** R
> max_int = 2147483647
> output = test(max_int + 1)
> */
> ```
> 
> I've tried to find a simple workaround, but I am unable yet.

It seems to be an issue only when using stack in C++. Both C and C++ apparently work also with much larger sizes:

`
    int **array = new int*[2];
    array[0] = (int*) malloc(4611686018427387903 * sizeof (int));
    array[1] = (int*) malloc(4611686018427387903 * sizeof (int));

   std::vector<int> vec(4611686018427387903);
`

I don't know if that's of any use, though ;-)

**Comment by marcosci** [comment]
I am playing around now with unsigned vectors, seems to work so far. Will rewrite get_pairs tomorrow.

I think it is going to be slower, hopefully not that much... Or are you arguing for a size limit for raster?

**Comment by Nowosad** [comment]
I think it is worth to take two possibilities into account: (1) size limit or (2) performance limit. We will need to check it and decide.

**Comment by mhesselbarth** [comment]
In case we are able to code a function for very large raster, that might be slower for small- and medium-sized raster, we can also use both and add an option (global?)-argument. In this case, we would have a faster version for small rasters and in case somebody wants to use a large one, there is the option...

**Comment by marcosci** [comment]
Hi @charshade17, are you still here? :yum: 

We tried to somehow fix it, it could work possibly ... the only problem is none of us has enough memory to try it out. Could you run:

```r 
devtools::install_github("r-spatialecology/landscapemetrics", ref = "rcpp_fix")
library(landscapemetrics)
library(raster)

test <- raster("lc_2008_4bit_clip.tif")
landscapemetrics:::rcpp_get_coocurrence_matrix(raster::as.matrix(test), as.matrix(4))
```

... and say if that works for you? If so, the next step would be to try out `lsm_p_contig()`.

**Comment by marcosci** [comment]
@Nowosad - at least for small raster the solution in the rcpp_fix branch seems to a bit faster, too:

```r
> microbenchmark::microbenchmark(
+ vector_return = rcpp_get_pairs2(mat, directions = as.matrix(4)),
+ matrix_return = rcpp_get_pairs(mat, directions = as.matrix(4)),
+ times = 99999
+ )
Unit: microseconds
          expr    min      lq     mean median     uq      max neval
 vector_return 19.657 32.0975 36.69469 34.234 36.181 35708.25 99999
 matrix_return 21.766 35.2885 38.73251 37.725 39.948 27500.43 99999
```

`get_pairs2` is the old solution from the master branch.

**Comment by Nowosad** [comment]
Ok, let me know when you have a working version and I will try it.

**Comment by mhesselbarth** [comment]
50dd6316 might fix the problem. At least, now everything is running for our datasets. However, I couldn't try the really large raster (not enough RAM). 

@charshade17, could you please try the following? 

``` 
devtools::install_github("r-spatialecology/landscapemetrics", ref = "rcpp_fix")

library(landscapemetrics)
library(raster)

test <- raster("lc_2008_4bit_clip.tif")

landscapemetrics:::rcpp_get_coocurrence_matrix(raster::as.matrix(test), as.matrix(4))

lsm_p_contig(test)
```

**Comment by charshade17** [comment]
Yes I'll try it out! Thanks guys!

**Comment by charshade17** [comment]
What version of R should I be using to do all of this? Every time I try to load the new landscapemtrics, it says I need "Rtools" which is not available for R 3.5.1

> devtools::install_github("r-spatialecology/landscapemetrics", ref = "rcpp_fix")
Downloading GitHub repo r-spatialecology/landscapemetrics@rcpp_fix
WARNING: Rtools is required to build R packages, but the version of Rtools previously installed in C:/Users/cshade/Documents/R/Rtools has been deleted.

Please download and install Rtools 3.5 from http://cran.r-project.org/bin/windows/Rtools/.
Error: Could not find tools necessary to compile a package
> 
> install.packages(Rtools)
Error in install.packages(Rtools) : object 'Rtools' not found
> install.packages("Rtools")
Installing package into ‘C:/Users/cshade/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
Warning message:
package ‘Rtools’ is not available (for R version 3.5.1)

**Comment by mhesselbarth** [comment]
You have to download and install RTools first. You can find it here [https://cran.r-project.org/bin/windows/Rtools/](https://cran.r-project.org/bin/windows/Rtools/)

**Comment by charshade17** [comment]
Right so I did that. It installed onto my local drive for some reason, so I copy and pasted the folder into my R library but it still says: Error in library(Rtools) : there is no package called ‘Rtools’

**Comment by charshade17** [comment]
Just kidding it's working, I realized I didn't have to load R tools, haha

**Comment by charshade17** [comment]
So I'm getting a different size error, but I think it's because my RAM is maxing out. I'm going to try on a different computer with more RAM tomorrow.

landscapemetrics:::rcpp_get_coocurrence_matrix(raster::as.matrix(test), as.matrix(4))
Error: cannot allocate vector of size 3.2 Gb

**Comment by bitbacchus** [comment]
@charshade17 you have 64-bit versions of Windows and R, right? 3.2 Gb sounds like it could be related to address space problems...

PS: I started commenting here because I'm sitting in the same office as Marco and next to Max' office and got somehow involved in their discussions on this topic ;-)

**Comment by marcosci** [comment]
Hm, so it runs through for me - but it only returns 0s.
Will try it on our HPC today, maybe it works there (I had to run it on my local disk, maybe that introduced errors).

Weirdly, if I run it with artificial data everything works fine:

```r
library(raster)
library(NLMR)
library(landscapetools)


# test <- readAll(raster("/home/marco/Desktop/lc_2008_4bit_clip.tif"))
test <- nlm_mosaictess(2500, 25000, germs = 20000)
test <- util_classify(test, weighting = c(0.5, 0.25, 0.25))

util_plot(test)

rcpp_get_coocurrence_matrix(raster::as.matrix(test), as.matrix(4))
```

**Comment by marcosci** [comment]
Took us a while, but your problem should be solved now :+1: 

```r 
devtools::install_github("r-spatialecology/landscapemetrics")

library(landscapemetrics)
library(raster)

test <- raster("lc_2008_4bit_clip.tif")

landscapemetrics:::rcpp_get_coocurrence_matrix(raster::as.matrix(test), as.matrix(4))

lsm_p_contig(test)
```

Can you confirm @charshade17 ?

**Comment by charshade17** [comment]
Unfortunately still not working :(

library(landscapemetrics)
library(raster)
Loading required package: sp
> 
> test <- raster("lc_2008_4bit_clip.tif")
> landscapemetrics:::rcpp_get_coocurrence_matrix(raster::as.matrix(test), as.matrix(4))
          1         2       3        4         5         6         7      8
1 255303212  10882210   16710   244868   1282275   1908944   3734944   2493
2  10882210 312207646  166952   188030   8179642   1541095  10597623  17188
3     16710    166952 5856294     1158      6101      3489     55299   5246
4    244868    188030    1158 85617498      2690     25482    104516     51
5   1282275   8179642    6101     2690 241032722     29646   7989931   2894
6   1908944   1541095    3489    25482     29646 160895768   8041845    512
7   3734944  10597623   55299   104516   7989931   8041845 304451808  21616
8      2493     17188    5246       51      2894       512     21616 543180
> lsm_p_contig(test)
**Error in rcpp_get_coocurrence_matrix(patch_mat, directions = as.matrix(diagonal_matrix)) : 
  std::bad_alloc**

**Comment by bitbacchus** [comment]
Hm, I can reproduce this and found part of the problem. 

Apparently, the landscape has 422838 individual patches of class `1` alone, and `rcpp_get_coocurrence_matrix` tries to compute a co-occurrence matrix of 422838*422838 elements. You'd need about 1.5 terabytes RAM to store this. 

It's likely a bug that came from 11a8d9a4d754ebee544ebcef42288f8ae857598d, what do you think?

**Comment by bitbacchus** [comment]
@marcosci, yes I think you're right, it's not really a bug anymore, it's a memory issue. This is probably not a quick fix...

@charshade17 are you aware that the result of this metric would be a tibble with approx. 3-4 million lines? Just to be sure this is actually what you expected.

**Comment by charshade17** [comment]
Oh my, no I was not aware of that. I thought there would just a result for each class. I'll have to explore some other metrics.

**Comment by marcosci** [comment]
You can try out show_patches, it shows you what you are looking at (given the size of your raster better set labels to false :sweat_smile :) ).

**Comment by bitbacchus** [comment]
So you want to use lsm_c_contig_mean? Makes more sense. However, it unfortunately won't work either, because it is currently based on lsm_p_contig. But this in principle a solvable problem.

**Comment by marcosci** [comment]
Nope, because you need the distribution of the patches to calculate the mean, sd and whatsoever. Every metric based on a summary stat would need to be changed on the patch level.

**Comment by bitbacchus** [comment]
OK, in 14f32bc41db04c2f1d83ef496570382cb59d574d I tweaked rcpp_get_cooccurrence_matrix to a new function rcpp_get_cooccurrence_matrix_diag that only computes the diagonal of the matrix and hence greatly reduces the amount of memory needed.

On my laptop, it took 40 minutes and ~20 Gb RAM to calculate `lsm_c_contig_mn` on @charshade17 's raster, the results are looking promising:

```R
# A tibble: 8 x 6
  layer level class    id metric    value
  <int> <chr> <int> <int> <chr>     <dbl>
1     1 class     1    NA contig_mn 0.545
2     1 class     2    NA contig_mn 0.459
3     1 class     3    NA contig_mn 0.587
4     1 class     4    NA contig_mn 0.583
5     1 class     5    NA contig_mn 0.815
6     1 class     6    NA contig_mn 0.414
7     1 class     7    NA contig_mn 0.379
8     1 class     8    NA contig_mn 0.524
```

Please test:
```R
devtools::install_github("r-spatialecology/landscapemetrics", ref = "get_unique_values2")

library(landscapemetrics)
library(raster)

landscape <- raster("lc_2008_4bit_clip.tif")

res <- lsm_c_contig_mn(landscape = landscape, directions = 4)
```

**Comment by mhesselbarth** [comment]
Not sure if I'm just stupid this mornining (well it is Monday...), but I get an error trying to build: `use of undeclared identifier 'get_patches_map;`

**Comment by bitbacchus** [comment]
@mhesselbarth, apparently I got a bit confused on what I already committed. It should work now :-)

**Comment by marcosci** [comment]
As this is already quite confusing here, I would close the issue now.
Some of the metrics now work for rasters as large as the one from @charshade17 , but others still need some tweaking.

Our goal for v0.4 should be that most of them are running then.

Feel free to reopen, if there are still issues with `lsm_c_contig_mn`
